//https://puni.sh/api/plugins
[
  {
    "Author": "Taurenkey, croizat",
    "Name": "Pandora's Box",
    "Punchline": "Do you dare to open Pandora's Box?",
    "Description": "Pandora's Box is a collection of major QoL tweaks and adjustments.\n\nOpen the box with /pandora",
    "Tags": [
      "punish",
      "plugin"
    ],
    "InternalName": "PandorasBox",
    "RepoUrl": "https://github.com/PunishXIV/PandorasBox",
    "DownloadCount": 130238,
    "LastUpdate": 1700756078220,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/8/PandorasBox/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/8/PandorasBox/versions/latest.zip",
    "AssemblyVersion": "1.5.3.5",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "- Active-Time Maneuver Solver should now work with Direct Chat mode and will close chat if open to keep mashing",
    "TestingAssemblyVersion": "1.5.4.0",
    "DownloadLinkTesting": "https://puni.sh/api/plugins/download/8/PandorasBox/versions/testing.zip",
    "IconUrl": "https://s3.puni.sh/media/plugin/8/icon-9opcpzqyh1h.png"
  },
  {
    "Author": "daemitus, kawaii",
    "Name": "Yes Already",
    "Punchline": "Clicks Yes in various dialogs you've specified.",
    "Description": "Tired of clicking yes in Praetorium? Can't stand using keys in dungeons? Well do I have the plugin for you! Yes Already is specifically designed to click all the annoying dialogs you've grown accustomed facerolling. Just enter the dialog text, and you'll never see it again! Also works with /regex/ and has several built-in modules for dialogs that aren't quite yes/no prompts but act like it (like desynth).",
    "Tags": [],
    "InternalName": "YesAlready",
    "RepoUrl": "https://github.com/PunishXIV/YesAlready",
    "DownloadCount": 39585,
    "LastUpdate": 1699458879203,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/26/YesAlready/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/26/YesAlready/versions/latest.zip",
    "AssemblyVersion": "1.4.0.3",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "",
    "TestingAssemblyVersion": "1.4.0.3",
    "DownloadLinkTesting": "https://puni.sh/api/plugins/download/26/YesAlready/versions/testing.zip",
    "IconUrl": "https://s3.puni.sh/media/plugin/26/icon-v1pvonkr6r.png"
  },
  {
    "Author": "NightmareXIV",
    "Name": "Splatoon",
    "Punchline": "Redefining FFXIV navigation with unlimited, precise waymarks.",
    "Description": "Splatoon is a powerful accessibility tool. It revolutionizes gameplay with its custom waymark system, offering the ability to create unlimited grouped waymarks, labels, and actor indicators with exacting pixel precision. This feature empowers players by making crucial objects and events more visually discernible, thereby facilitating quicker reactions. However, it's important to note that the plugin does not come pre-loaded with presets. Players have the freedom to craft their own or import existing ones, offering a personalized touch to their gaming experience.",
    "Tags": [
      "Utility",
      "Accessibility"
    ],
    "InternalName": "Splatoon",
    "RepoUrl": "https://github.com/PunishXIV/Splatoon",
    "DownloadCount": 160644,
    "LastUpdate": 1699397772599,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/10/Splatoon/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/10/Splatoon/versions/latest.zip",
    "AssemblyVersion": "3.4.0.7",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "",
    "TestingAssemblyVersion": "3.5.0.1",
    "DownloadLinkTesting": "https://puni.sh/api/plugins/download/10/Splatoon/versions/testing.zip",
    "IconUrl": "https://s3.puni.sh/media/plugin/10/icon-cchf5yumm2p.png"
  },
  {
    "Author": "Taurenkey, Gidedin",
    "Name": "LazyLoot",
    "Punchline": "Dungeon Loot but Lazy.",
    "Description": "Roll command with various arguments need | needonly | greed | pass | passall. \nChat and Toast output and delay for rolling.",
    "Tags": [
      "plugin",
      "loot",
      "utility",
      "other"
    ],
    "InternalName": "LazyLoot",
    "RepoUrl": "https://github.com/PunishXIV/LazyLoot",
    "DownloadCount": 36638,
    "LastUpdate": 1697274016656,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/9/LazyLoot/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/9/LazyLoot/versions/latest.zip",
    "AssemblyVersion": "5.2.0.2",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "Attempt to fix crashing",
    "TestingAssemblyVersion": "5.2.0.2",
    "DownloadLinkTesting": "https://puni.sh/api/plugins/download/9/LazyLoot/versions/testing.zip",
    "IconUrl": "https://s3.puni.sh/media/plugin/9/icon-zjun2qgmfbe.png"
  },
  {
    "Author": "kawaii, NightmareXIV",
    "Name": "AutoRetainer",
    "Punchline": "Collect and assign ventures to your retainers from the comfort of your bed.",
    "Description": "Collect and assign ventures to your retainers from the comfort of your bed.",
    "Tags": [],
    "InternalName": "AutoRetainer",
    "RepoUrl": "https://github.com/PunishXIV/AutoRetainer",
    "DownloadCount": 205839,
    "LastUpdate": 1700791334364,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/24/AutoRetainer/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/24/AutoRetainer/versions/latest.zip",
    "AssemblyVersion": "4.2.2.5",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "",
    "TestingAssemblyVersion": "4.2.3.0",
    "DownloadLinkTesting": "https://puni.sh/api/plugins/download/24/AutoRetainer/versions/testing.zip",
    "IconUrl": "https://s3.puni.sh/media/plugin/24/icon-drb6aywk5m9.png"
  },
  {
    "Author": "Taurenkey",
    "Name": "Artisan",
    "Punchline": "A 'simple' crafting plugin.",
    "Description": "The all-in-one crafting plugin.",
    "Tags": [
      "crafting"
    ],
    "InternalName": "Artisan",
    "RepoUrl": "https://github.com/PunishXIV/Artisan",
    "DownloadCount": 372378,
    "LastUpdate": 1701446932246,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/6/Artisan/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/6/Artisan/versions/latest.zip",
    "AssemblyVersion": "2.1.1.7",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "- Adds new \"Progress Priority CP Threshold\" under solver settings.\n- Attempt to fix FPS issues with the list editor on the ingredients tab.",
    "TestingAssemblyVersion": "2.1.1.2",
    "DownloadLinkTesting": "https://puni.sh/api/plugins/download/6/Artisan/versions/testing.zip",
    "IconUrl": "https://s3.puni.sh/media/plugin/6/icon-3h8wd5b9qr.png"
  },
  {
    "Author": "kawaii, NightmareXIV",
    "Name": "Avarice",
    "Punchline": "Positional feedback with pixel perfect rear/flank tracking, range indicators, and more.",
    "Description": "Positional feedback with pixel perfect rear/flank tracking, range indicators, and more.",
    "Tags": [
      "combat"
    ],
    "InternalName": "Avarice",
    "RepoUrl": "https://github.com/PunishXIV/Avarice",
    "DownloadCount": 37090,
    "LastUpdate": 1699389412236,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/11/Avarice/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/11/Avarice/versions/latest.zip",
    "AssemblyVersion": "2.0.3.9",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "",
    "IconUrl": "https://s3.puni.sh/media/plugin/11/icon-d95r9462spc.png"
  },
  {
    "Author": "kawaii, NightmareXIV",
    "Name": "Orbwalker",
    "Punchline": "S P A C E G L I D I N G",
    "Description": "Locks player movement while casting and allows for maximum caster uptime during the course of a fight.",
    "Tags": [],
    "InternalName": "Orbwalker",
    "RepoUrl": "https://github.com/PunishXIV/Orbwalker",
    "DownloadCount": 9160,
    "LastUpdate": 1696968937655,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/12/Orbwalker/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/12/Orbwalker/versions/latest.zip",
    "AssemblyVersion": "1.0.0.4",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "",
    "IconUrl": "https://s3.puni.sh/media/plugin/12/icon-o94qaw6cyn.png"
  },
  {
    "Author": "kawaii",
    "Name": "Palace Pal",
    "Punchline": "Shows possible trap & Accursed Hoard locations in Palace of The Dead, Heaven on High, and Eureka Orthos.",
    "Description": "Shows possible trap & Accursed Hoard locations in Palace of The Dead, Heaven on High, and Eureka Orthos.\n\nThis plugin requires Splatoon in order to render various draws on the screen.",
    "Tags": [
      "potd",
      "hoh",
      "splatoon",
      "palace"
    ],
    "InternalName": "PalacePal",
    "RepoUrl": "https://github.com/PunishXIV/PalacePal",
    "DownloadCount": 27758,
    "LastUpdate": 1696635551820,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/32/PalacePal/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/32/PalacePal/versions/latest.zip",
    "AssemblyVersion": "4.8.0.3",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "",
    "IconUrl": "https://s3.puni.sh/media/plugin/32/icon-vrl2a8dqi3h.png"
  },
  {
    "Author": "Taurenkey",
    "Name": "Saucy",
    "Punchline": "When working for MGP is too much effort.",
    "Description": "Automates certain Gold Saucer mini-games.",
    "Tags": [
      "gold saucer",
      "mgp",
      "automation"
    ],
    "InternalName": "Saucy",
    "RepoUrl": "https://github.com/PunishXIV/Saucy",
    "DownloadCount": 63421,
    "LastUpdate": 1696597899287,
    "DownloadLinkInstall": "https://puni.sh/api/plugins/download/7/Saucy/versions/latest.zip",
    "DownloadLinkUpdate": "https://puni.sh/api/plugins/download/7/Saucy/versions/latest.zip",
    "AssemblyVersion": "1.3.0.2",
    "ApplicableVersion": "any",
    "DalamudApiLevel": "9",
    "Changelog": "Fix Triple Triad sometimes not playing",
    "IconUrl": "https://s3.puni.sh/media/plugin/7/icon-bl3wub19h2u.png"
  }
]
